insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (1, 'Drywall & Acoustical (FED)', '2023/09/01', 'Lefty Howlett');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (2, 'Site Furnishings', '2024/03/06', 'Rosalie Brouard');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (3, 'Masonry & Precast', '2023/05/27', 'Cole Foyston');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (4, 'Plumbing & Medical Gas', '2024/01/14', 'Waverly O''Sherin');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (5, 'Drywall & Acoustical (MOB)', '2024/01/25', 'Basil Crowley');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (6, 'RF Shielding', '2023/06/30', 'Aurelia Holdren');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (7, 'Electrical and Fire Alarm', '2023/07/31', 'Mischa Geator');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (8, 'Granite Surfaces', '2024/02/19', 'Andriana Tyson');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (9, 'Doors, Frames & Hardware', '2023/07/29', 'Quill Sherbrook');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (10, 'Epoxy Flooring', '2023/11/15', 'Thain Laminman');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (11, 'Doors, Frames & Hardware', '2024/01/17', 'Emilee Joynson');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (12, 'Overhead Doors', '2024/02/05', 'Dolores Petch');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (13, 'Electrical', '2023/06/07', 'Mattie Tolworthy');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (14, 'Framing (Steel)', '2023/09/07', 'Annabela Gooddie');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (15, 'Ornamental Railings', '2023/10/10', 'Sibyl Saunier');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (16, 'Construction Clean and Final Clean', '2023/05/11', 'Jackelyn Greeve');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (17, 'Marlite Panels (FED)', '2023/04/29', 'Kermy Catherall');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (18, 'Granite Surfaces', '2023/12/06', 'Jane Pettett');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (19, 'Rebar & Wire Mesh Install', '2023/05/16', 'Stefanie Tresler');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (20, 'Overhead Doors', '2023/09/15', 'Reiko Monkman');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (21, 'RF Shielding', '2023/04/26', 'Alexandro Ucchino');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (22, 'HVAC', '2023/10/24', 'Grant Gavin');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (23, 'Construction Clean and Final Clean', '2023/10/07', 'Linzy Astlet');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (24, 'Granite Surfaces', '2023/04/27', 'Cozmo Brightling');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (25, 'Construction Clean and Final Clean', '2024/04/13', 'Denni Sindell');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (26, 'HVAC', '2024/03/22', 'Jessie Ebourne');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (27, 'Prefabricated Aluminum Metal Canopies', '2023/06/25', 'Samuele Bowness');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (28, 'Soft Flooring and Base', '2023/07/21', 'Luz Badsey');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (29, 'Site Furnishings', '2023/05/11', 'Chad Daile');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (30, 'HVAC', '2023/06/28', 'Waylin Trehearne');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (31, 'Painting & Vinyl Wall Covering', '2023/09/12', 'Cassie Blamire');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (32, 'Ornamental Railings', '2023/11/23', 'Gabi Dils');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (33, 'Fire Sprinkler System', '2023/08/12', 'Mireielle Tibalt');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (34, 'RF Shielding', '2023/05/14', 'Dawn Flannery');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (35, 'Curb & Gutter', '2023/04/30', 'Julian Fransewich');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (36, 'Masonry & Precast', '2024/04/01', 'Silvain McKerton');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (37, 'Drilled Shafts', '2023/06/24', 'Kristopher Putley');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (38, 'Rebar & Wire Mesh Install', '2024/03/02', 'Terence Poles');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (39, 'Ornamental Railings', '2023/11/19', 'Paulina Corwood');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (40, 'Casework', '2023/06/12', 'Glen Riches');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (41, 'Masonry & Precast', '2023/06/15', 'Valeria Lipsett');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (42, 'EIFS', '2023/05/31', 'Kath Rossbrooke');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (43, 'Epoxy Flooring', '2023/12/21', 'Harrietta Pleasaunce');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (44, 'Sitework & Site Utilities', '2023/06/11', 'Lorne Noades');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (45, 'Fire Protection', '2023/10/27', 'Felicity Whitcher');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (46, 'Wall Protection', '2023/11/24', 'Nance Tappor');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (47, 'Temp Fencing, Decorative Fencing and Gates', '2023/05/30', 'Booth Jonathon');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (48, 'Elevator', '2023/12/29', 'Victoria Dunbobin');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (49, 'Casework', '2023/07/08', 'Doralia Chitson');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (50, 'Prefabricated Aluminum Metal Canopies', '2023/11/20', 'Orelee Newbigging');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (51, 'Construction Clean and Final Clean', '2024/04/05', 'Ephraim Pollak');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (52, 'Painting & Vinyl Wall Covering', '2024/02/11', 'Lucias Kohtler');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (53, 'Wall Protection', '2023/12/23', 'Joycelin Bagnal');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (54, 'Wall Protection', '2023/06/20', 'Gare Rumke');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (55, 'Ornamental Railings', '2024/03/16', 'Selma Fysh');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (56, 'Structural and Misc Steel (Fabrication)', '2023/05/07', 'Ferdinanda Brockherst');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (57, 'Electrical', '2023/12/21', 'Sacha Mutimer');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (58, 'Curb & Gutter', '2023/11/02', 'Darrick Lawtey');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (59, 'Framing (Steel)', '2024/01/11', 'Corabel Heynen');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (60, 'Doors, Frames & Hardware', '2023/04/27', 'Celene Knowles');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (61, 'Overhead Doors', '2024/03/05', 'Shayna Jessett');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (62, 'Granite Surfaces', '2024/02/17', 'Lazarus Bentham3');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (63, 'RF Shielding', '2023/09/15', 'Mariette Bartles');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (64, 'Electrical and Fire Alarm', '2023/09/08', 'Carlos Trewartha');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (65, 'Glass & Glazing', '2024/02/24', 'Jacinta Brennans');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (66, 'Roofing (Metal)', '2024/02/29', 'Wendi Dessant');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (67, 'Drilled Shafts', '2023/04/27', 'Iormina Foulkes');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (68, 'Masonry & Precast', '2024/02/19', 'Eolanda Theseira');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (69, 'Fire Protection', '2023/06/21', 'Ulrikaumeko Thoumas');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (70, 'Termite Control', '2024/02/11', 'Jasun Di Angelo');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (71, 'Drywall & Acoustical (FED)', '2023/09/25', 'Ashbey Lombard');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (72, 'Roofing (Metal)', '2023/05/17', 'Alf Pittson');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (73, 'Structural & Misc Steel Erection', '2023/09/29', 'Persis Tomsa');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (74, 'Rebar & Wire Mesh Install', '2024/02/04', 'Aggi Buddle');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (75, 'Temp Fencing, Decorative Fencing and Gates', '2023/06/18', 'Solomon Jacketts');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (76, 'Ornamental Railings', '2023/09/21', 'Cristine Border');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (77, 'Fire Protection', '2023/06/03', 'Alister Robak');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (78, 'Casework', '2023/10/02', 'Garvin Hullyer');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (79, 'Hard Tile & Stone', '2023/11/10', 'Barret Garrad');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (80, 'Ornamental Railings', '2023/04/25', 'Roley Golland');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (81, 'Epoxy Flooring', '2024/02/06', 'Elnar Gritsaev');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (82, 'Drilled Shafts', '2023/09/02', 'Ketti Jerosch');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (83, 'Waterproofing & Caulking', '2023/06/15', 'Horatio Huscroft');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (84, 'Painting & Vinyl Wall Covering', '2023/07/26', 'Raddie Heikkinen');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (85, 'Overhead Doors', '2024/02/20', 'Ely Cuttles');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (86, 'EIFS', '2024/03/01', 'Kele Venners');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (87, 'Framing (Wood)', '2023/04/26', 'Bernhard Hourstan');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (88, 'Epoxy Flooring', '2023/05/10', 'Latia Cluatt');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (89, 'Ornamental Railings', '2024/03/21', 'Teresa Madgwick');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (90, 'Painting & Vinyl Wall Covering', '2024/02/29', 'Leoline Roscamps');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (91, 'Soft Flooring and Base', '2024/02/14', 'Abey Jellybrand');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (92, 'Overhead Doors', '2024/02/07', 'Addia Pinsent');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (93, 'Epoxy Flooring', '2023/09/07', 'Denis Rivelin');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (94, 'Landscaping & Irrigation', '2023/05/26', 'Al Dalley');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (95, 'Electrical', '2023/11/04', 'Nadeen Dabney');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (96, 'Ornamental Railings', '2023/12/07', 'Martino Shellcross');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (97, 'Rebar & Wire Mesh Install', '2023/07/14', 'Fionna Tunnoch');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (98, 'Waterproofing & Caulking', '2023/08/25', 'Benoit Bedborough');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (99, 'Roofing (Metal)', '2023/10/11', 'Karyl Patzelt');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (100, 'Casework', '2023/12/13', 'Marley Winwright');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (101, 'HVAC', '2023/05/12', 'Dorree Aronoff');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (102, 'Epoxy Flooring', '2023/08/12', 'Reed Kilmurray');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (103, 'Termite Control', '2023/08/11', 'Cross Balffye');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (104, 'Temp Fencing, Decorative Fencing and Gates', '2024/02/11', 'Carol Rumgay');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (105, 'Roofing (Asphalt)', '2024/01/14', 'Shoshana Sparrowe');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (106, 'Roofing (Metal)', '2023/05/02', 'Shelbi Klesel');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (107, 'RF Shielding', '2024/03/09', 'Leah Da Costa');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (108, 'Granite Surfaces', '2023/07/28', 'Ramonda Blencowe');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (109, 'Construction Clean and Final Clean', '2024/01/02', 'Felic Pargiter');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (110, 'Hard Tile & Stone', '2023/07/04', 'Letitia Langmuir');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (111, 'Structural & Misc Steel Erection', '2023/09/18', 'Steffen Willbraham');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (112, 'Curb & Gutter', '2024/03/31', 'Meredith McGillacoell');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (113, 'Rebar & Wire Mesh Install', '2024/02/23', 'Aluino Jochanany');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (114, 'Soft Flooring and Base', '2023/09/21', 'Leah Durban');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (115, 'Framing (Wood)', '2023/05/29', 'Wade O''Flannery');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (116, 'Drywall & Acoustical (MOB)', '2024/03/19', 'Pail Cyster');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (117, 'Masonry', '2024/01/04', 'Hesther Hindge');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (118, 'Casework', '2024/02/06', 'Aldo Delacourt');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (119, 'Fire Sprinkler System', '2023/11/01', 'Elmo Nickols');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (120, 'Hard Tile & Stone', '2024/03/30', 'Dru Arnaudet');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (121, 'Overhead Doors', '2023/06/11', 'Claudina Baudoux');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (122, 'Termite Control', '2023/11/26', 'Jan Ciardo');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (123, 'Electrical', '2023/05/19', 'Sheelah Kettlewell');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (124, 'Rebar & Wire Mesh Install', '2023/08/19', 'Ethelind O''Shevlan');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (125, 'RF Shielding', '2023/08/13', 'Lavinia Samet');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (126, 'Structural & Misc Steel Erection', '2024/02/09', 'Axel Brisley');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (127, 'Painting & Vinyl Wall Covering', '2024/02/11', 'Jehanna McQuin');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (128, 'Wall Protection', '2023/09/01', 'Nevsa Drews');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (129, 'Curb & Gutter', '2023/08/11', 'Egor Mayhow');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (130, 'Landscaping & Irrigation', '2023/06/18', 'Cleveland Philipps');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (131, 'Painting & Vinyl Wall Covering', '2023/11/14', 'Nevsa Polack');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (132, 'Elevator', '2024/03/26', 'Frank Sabati');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (133, 'Temp Fencing, Decorative Fencing and Gates', '2023/11/02', 'Gardy Creser');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (134, 'Roofing (Metal)', '2023/08/13', 'Rubie Langlais');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (135, 'Electrical and Fire Alarm', '2024/04/06', 'Juan Talmadge');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (136, 'Electrical', '2023/07/06', 'Gretchen Allington');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (137, 'Asphalt Paving', '2023/12/17', 'Esmaria Latus');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (138, 'Prefabricated Aluminum Metal Canopies', '2024/01/01', 'Elisabet Licciardi');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (139, 'Overhead Doors', '2023/10/07', 'Goraud Surgeoner');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (140, 'Temp Fencing, Decorative Fencing and Gates', '2023/06/10', 'Luther MacGillivrie');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (141, 'Ornamental Railings', '2024/01/26', 'Pepito Burrass');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (142, 'Hard Tile & Stone', '2023/08/27', 'Marie Adrain');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (143, 'Masonry & Precast', '2023/11/25', 'Aldric Charlotte');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (144, 'Wall Protection', '2023/08/28', 'Constantia McKevany');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (145, 'Elevator', '2023/12/03', 'Abrahan Garraway');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (146, 'Rebar & Wire Mesh Install', '2023/04/20', 'Ludwig Everett');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (147, 'Epoxy Flooring', '2023/10/02', 'Konstanze Osipenko');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (148, 'Masonry', '2024/01/04', 'Jan Cornwall');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (149, 'Fire Protection', '2023/05/19', 'Eleen Caze');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (150, 'Termite Control', '2023/08/16', 'Howie Flewin');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (151, 'Electrical and Fire Alarm', '2024/02/25', 'Maryanna Arstall');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (152, 'Framing (Steel)', '2023/10/29', 'Zorine Moorhouse');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (153, 'Epoxy Flooring', '2024/01/27', 'Lurline Whiteford');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (154, 'Plumbing & Medical Gas', '2023/08/02', 'Fredrika Wong');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (155, 'Retaining Wall and Brick Pavers', '2023/08/01', 'Inna Abramchik');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (156, 'Roofing (Asphalt)', '2023/10/13', 'Ulick Codron');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (157, 'Structural and Misc Steel (Fabrication)', '2023/06/11', 'Nolie Cathrall');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (158, 'Landscaping & Irrigation', '2023/10/23', 'Kearney Caves');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (159, 'Exterior Signage', '2023/06/09', 'Cloris Fibbens');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (160, 'Plumbing & Medical Gas', '2023/09/22', 'Viole Tames');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (161, 'Landscaping & Irrigation', '2024/01/17', 'Thain Fitzer');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (162, 'Plumbing & Medical Gas', '2024/03/22', 'Lorilyn Whitta');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (163, 'Framing (Steel)', '2023/09/20', 'Sybyl Jakov');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (164, 'Structural & Misc Steel Erection', '2023/07/15', 'Dolf Bedinn');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (165, 'Elevator', '2023/11/18', 'Ancell Prise');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (166, 'Framing (Steel)', '2023/10/08', 'Lydon Nawton');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (167, 'Electrical', '2023/09/13', 'Orbadiah Woolpert');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (168, 'Plumbing & Medical Gas', '2024/04/13', 'Theo Phelip');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (169, 'Plumbing & Medical Gas', '2024/02/09', 'Roman Halms');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (170, 'Marlite Panels (FED)', '2023/07/17', 'Elianore Tarplee');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (171, 'Hard Tile & Stone', '2024/03/04', 'Delila Clewley');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (172, 'Landscaping & Irrigation', '2023/11/30', 'Michel Hairyes');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (173, 'Plumbing & Medical Gas', '2024/02/02', 'Ramsay Comben');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (174, 'Exterior Signage', '2024/01/07', 'Hillier Solloway');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (175, 'RF Shielding', '2024/02/12', 'Mercie Mayou');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (176, 'Doors, Frames & Hardware', '2024/02/16', 'Ellary Duthy');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (177, 'Elevator', '2023/10/23', 'Colleen Lympany');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (178, 'Epoxy Flooring', '2023/07/23', 'Ami Clewarth');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (179, 'Temp Fencing, Decorative Fencing and Gates', '2024/01/03', 'Elvina Siuda');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (180, 'Painting & Vinyl Wall Covering', '2023/11/12', 'Jill Moorwood');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (181, 'Framing (Wood)', '2023/09/14', 'Waylon Slyne');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (182, 'Rebar & Wire Mesh Install', '2024/02/13', 'Delly Kitteridge');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (183, 'Drywall & Acoustical (MOB)', '2023/11/26', 'Alvis Mistry');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (184, 'Waterproofing & Caulking', '2023/12/28', 'Berte Levi');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (185, 'Fire Sprinkler System', '2024/04/01', 'Thorsten Anfusso');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (186, 'Framing (Wood)', '2023/08/31', 'Meggie Spurryer');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (187, 'Drywall & Acoustical (FED)', '2024/01/20', 'Wye Mossop');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (188, 'Roofing (Asphalt)', '2024/03/11', 'Randi Garlicke');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (189, 'Electrical', '2024/03/16', 'Courtney Vallow');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (190, 'Fire Protection', '2023/08/17', 'Neal Gauvin');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (191, 'Elevator', '2024/02/13', 'Tiff Galiero');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (192, 'Asphalt Paving', '2023/08/10', 'Jermayne McCrone');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (193, 'Doors, Frames & Hardware', '2023/07/21', 'Wiatt Le Conte');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (194, 'Plumbing & Medical Gas', '2023/10/28', 'Brinna Loffhead');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (195, 'Construction Clean and Final Clean', '2024/02/11', 'Galvin Havers');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (196, 'Roofing (Metal)', '2023/08/22', 'Jenica Maundrell');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (197, 'Painting & Vinyl Wall Covering', '2024/02/14', 'Shawnee Lafford');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (198, 'Doors, Frames & Hardware', '2023/11/07', 'Wilma Tenwick');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (199, 'Soft Flooring and Base', '2023/06/04', 'Daveta Hesser');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (200, 'Electrical', '2023/11/04', 'Parsifal Northen');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (201, 'Elevator', '2023/07/12', 'Bart Wyche');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (202, 'Plumbing & Medical Gas', '2023/12/15', 'Drona McSperron');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (203, 'Rebar & Wire Mesh Install', '2024/02/04', 'Tine Kiely');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (204, 'Temp Fencing, Decorative Fencing and Gates', '2023/06/27', 'Jennee Carp');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (205, 'Landscaping & Irrigation', '2023/12/21', 'Clair Churms');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (206, 'Ornamental Railings', '2023/12/14', 'Gwennie Sayse');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (207, 'Electrical and Fire Alarm', '2023/10/16', 'Ursola Grave');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (208, 'Fire Sprinkler System', '2023/10/06', 'Nicol Fruser');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (209, 'Site Furnishings', '2024/01/28', 'Oby Castellan');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (210, 'Drywall & Acoustical (FED)', '2023/05/09', 'Bern Camacke');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (211, 'Doors, Frames & Hardware', '2024/03/12', 'Doti Noli');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (212, 'Roofing (Asphalt)', '2023/10/17', 'Stormi Foard');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (213, 'Framing (Wood)', '2023/12/14', 'Bart Letchmore');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (214, 'Landscaping & Irrigation', '2023/10/04', 'Sabrina Hatchard');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (215, 'Roofing (Metal)', '2024/02/17', 'Delores Nutbean');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (216, 'Elevator', '2023/10/26', 'Alain Cahill');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (217, 'Construction Clean and Final Clean', '2023/08/13', 'Heddie Franceschielli');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (218, 'Rebar & Wire Mesh Install', '2023/12/16', 'Eldredge Hastewell');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (219, 'Electrical', '2023/09/06', 'Berton Mantrup');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (220, 'Retaining Wall and Brick Pavers', '2023/10/15', 'Cris Barette');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (221, 'Prefabricated Aluminum Metal Canopies', '2024/03/09', 'Shell Mance');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (222, 'Epoxy Flooring', '2023/10/23', 'Swen Quinnet');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (223, 'Retaining Wall and Brick Pavers', '2023/12/03', 'Lianna Bastie');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (224, 'Sitework & Site Utilities', '2024/03/29', 'Helge Nelles');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (225, 'Asphalt Paving', '2023/07/21', 'Ernie Jobbins');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (226, 'Rebar & Wire Mesh Install', '2023/07/30', 'Ruggiero Preshous');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (227, 'Construction Clean and Final Clean', '2023/12/25', 'Tani Lindberg');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (228, 'Wall Protection', '2023/12/16', 'Drucill Nerney');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (229, 'HVAC', '2023/07/04', 'Osbourn Botterill');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (230, 'Ornamental Railings', '2023/05/18', 'Sigismund Simmen');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (231, 'Drywall & Acoustical (MOB)', '2023/12/07', 'Christen Van der Linde');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (232, 'EIFS', '2024/04/03', 'Berne Bonett');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (233, 'Structural & Misc Steel Erection', '2023/09/15', 'Mitchael Yakovlev');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (234, 'RF Shielding', '2023/10/23', 'Alisa Phelps');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (235, 'Temp Fencing, Decorative Fencing and Gates', '2024/02/19', 'Shelley Skey');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (236, 'Elevator', '2023/04/24', 'Minnaminnie Laughton');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (237, 'Drywall & Acoustical (FED)', '2024/02/16', 'Waring Render');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (238, 'Marlite Panels (FED)', '2024/04/13', 'Earle Gregoli');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (239, 'Epoxy Flooring', '2023/06/15', 'Emile Jefferys');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (240, 'Drywall & Acoustical (MOB)', '2023/10/10', 'Dorothea Luckett');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (241, 'HVAC', '2023/06/13', 'Lenna Klimaszewski');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (242, 'Glass & Glazing', '2024/02/22', 'Nev Partkya');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (243, 'Fire Protection', '2023/07/13', 'Mikol Keenor');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (244, 'Plumbing & Medical Gas', '2023/07/11', 'Charlean Huffadine');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (245, 'Exterior Signage', '2023/08/02', 'Goldarina Cromarty');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (246, 'RF Shielding', '2023/07/20', 'Carissa Loffill');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (247, 'Hard Tile & Stone', '2024/03/03', 'Cchaddie Cicero');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (248, 'Electrical and Fire Alarm', '2024/03/22', 'Bari Kelsall');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (249, 'Soft Flooring and Base', '2024/01/12', 'Cari Holmyard');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (250, 'Soft Flooring and Base', '2023/06/26', 'Humberto Concannon');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (251, 'Masonry', '2023/12/08', 'Lurline MacDonagh');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (252, 'Marlite Panels (FED)', '2023/11/15', 'Camille Algore');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (253, 'Temp Fencing, Decorative Fencing and Gates', '2024/01/22', 'Talyah Fookes');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (254, 'Ornamental Railings', '2024/02/03', 'Tarrah Tarte');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (255, 'Electrical', '2024/02/20', 'Anselma Camis');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (256, 'Sitework & Site Utilities', '2023/12/16', 'Elbertina Reason');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (257, 'Framing (Wood)', '2023/08/19', 'Neville Southerell');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (258, 'Sitework & Site Utilities', '2024/01/03', 'Adah Sines');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (259, 'Glass & Glazing', '2023/11/26', 'Josh Ivermee');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (260, 'RF Shielding', '2023/12/02', 'Joel Crease');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (261, 'Painting & Vinyl Wall Covering', '2023/10/04', 'Link Gudgion');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (262, 'Granite Surfaces', '2023/08/03', 'Boycey O''Bradden');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (263, 'RF Shielding', '2023/06/13', 'Kylie Brolan');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (264, 'Plumbing & Medical Gas', '2023/10/25', 'Giorgia Senechault');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (265, 'Termite Control', '2023/05/31', 'Theadora Salmen');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (266, 'Construction Clean and Final Clean', '2023/07/07', 'Corliss Flexman');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (267, 'Marlite Panels (FED)', '2024/04/13', 'Maggie Skentelbury');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (268, 'Roofing (Metal)', '2023/11/15', 'Leona Steptoe');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (269, 'Waterproofing & Caulking', '2023/09/10', 'Mikaela Van Velden');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (270, 'Hard Tile & Stone', '2023/12/01', 'Gardy Molden');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (271, 'Fire Protection', '2023/04/23', 'Belva Gaine of England');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (272, 'Doors, Frames & Hardware', '2023/06/28', 'Bastien Burndred');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (273, 'Roofing (Metal)', '2024/03/25', 'Henry Kubanek');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (274, 'Asphalt Paving', '2024/02/01', 'Domenic Kiera');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (275, 'Masonry', '2023/09/26', 'Louisette O''Clery');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (276, 'Fire Protection', '2023/08/21', 'Jaclyn Ornillos');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (277, 'Framing (Wood)', '2024/01/16', 'Thacher Gregor');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (278, 'Exterior Signage', '2023/07/24', 'Jessey Loweth');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (279, 'Rebar & Wire Mesh Install', '2023/05/30', 'Westley Andreichik');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (280, 'Fire Protection', '2024/03/12', 'Herbert Wagner');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (281, 'Landscaping & Irrigation', '2023/11/01', 'Hayyim Piburn');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (282, 'Construction Clean and Final Clean', '2024/02/09', 'Emmi Archambault');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (283, 'Framing (Steel)', '2024/03/08', 'Malanie Hawkey');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (284, 'Ornamental Railings', '2023/07/23', 'Carlee Fairn');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (285, 'Landscaping & Irrigation', '2023/08/26', 'Cordi Diehn');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (286, 'Fire Sprinkler System', '2023/11/13', 'Heindrick Huke');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (287, 'Overhead Doors', '2024/03/17', 'Bartie Kendrew');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (288, 'Asphalt Paving', '2024/03/27', 'Rasla Strephan');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (289, 'Plumbing & Medical Gas', '2024/02/04', 'Mina Plowright');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (290, 'EIFS', '2024/01/03', 'Emalia Sappell');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (291, 'Exterior Signage', '2023/07/13', 'Ode Wisker');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (292, 'Ornamental Railings', '2024/03/23', 'Marysa Sympson');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (293, 'Drywall & Acoustical (MOB)', '2023/09/08', 'Lela Scryne');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (294, 'Painting & Vinyl Wall Covering', '2023/12/27', 'Adamo Myott');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (295, 'Framing (Steel)', '2023/05/13', 'Roobbie Dorgon');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (296, 'Marlite Panels (FED)', '2024/03/24', 'Taddeusz Dmitrienko');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (297, 'HVAC', '2023/05/09', 'Darbie Galego');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (298, 'Painting & Vinyl Wall Covering', '2023/06/14', 'Orsa Dolton');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (299, 'Hard Tile & Stone', '2023/12/23', 'Miquela Cottam');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (300, 'Elevator', '2024/04/03', 'Orlan Covey');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (301, 'Soft Flooring and Base', '2023/05/24', 'Dall Gowrich');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (302, 'Termite Control', '2023/08/01', 'Juliana Haglington');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (303, 'Painting & Vinyl Wall Covering', '2023/04/26', 'Tersina Draisey');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (304, 'Landscaping & Irrigation', '2023/12/27', 'Carolann Cocks');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (305, 'Curb & Gutter', '2024/02/04', 'Lorianna Suggate');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (306, 'Waterproofing & Caulking', '2024/04/05', 'Mose Lowings');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (307, 'Hard Tile & Stone', '2024/01/09', 'Tynan Rosendorf');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (308, 'Plumbing & Medical Gas', '2023/10/20', 'Erhard Almeida');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (309, 'Prefabricated Aluminum Metal Canopies', '2023/05/30', 'Gwenny Tufts');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (310, 'Roofing (Metal)', '2023/06/26', 'Norean Cufflin');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (311, 'Masonry', '2023/07/07', 'Selby Stearn');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (312, 'Doors, Frames & Hardware', '2024/02/29', 'Alaster De Cristoforo');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (313, 'Construction Clean and Final Clean', '2024/02/07', 'Griffin Farrah');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (314, 'Waterproofing & Caulking', '2024/01/09', 'Shandra Loding');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (315, 'Overhead Doors', '2023/10/07', 'Chadwick Tolcharde');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (316, 'Overhead Doors', '2023/06/11', 'Corrianne Orry');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (317, 'Elevator', '2023/10/03', 'Noe Porter');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (318, 'HVAC', '2023/10/21', 'Alastair Siney');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (319, 'Epoxy Flooring', '2023/11/19', 'Merla Surphliss');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (320, 'Rebar & Wire Mesh Install', '2023/09/20', 'Elie Di Antonio');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (321, 'Construction Clean and Final Clean', '2023/06/16', 'Joana Spacie');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (322, 'Sitework & Site Utilities', '2024/04/10', 'Tomas Gamble');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (323, 'Elevator', '2023/10/20', 'Ole Tindle');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (324, 'Rebar & Wire Mesh Install', '2023/10/31', 'Sybyl Scadding');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (325, 'Landscaping & Irrigation', '2024/04/11', 'Marsha Partkya');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (326, 'Epoxy Flooring', '2024/04/08', 'Merv Fone');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (327, 'Site Furnishings', '2023/12/25', 'Zulema Cicco');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (328, 'Sitework & Site Utilities', '2023/12/24', 'Cristen Di Francecshi');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (329, 'Masonry', '2023/12/18', 'Meaghan Rosenwald');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (330, 'Fire Protection', '2023/12/14', 'Mandy Partlett');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (331, 'Elevator', '2023/10/30', 'Malcolm Lumbers');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (332, 'Drywall & Acoustical (MOB)', '2024/03/31', 'Trixie Fairpo');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (333, 'RF Shielding', '2023/05/02', 'Martynne Lagneaux');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (334, 'Marlite Panels (FED)', '2024/01/04', 'Jeanelle Povah');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (335, 'Plumbing & Medical Gas', '2023/06/06', 'Virgilio Maliphant');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (336, 'Curb & Gutter', '2024/03/14', 'Krystyna Somerville');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (337, 'Masonry', '2024/03/04', 'Son Beech');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (338, 'Structural & Misc Steel Erection', '2023/10/03', 'Bethina Doniso');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (339, 'Masonry & Precast', '2023/08/28', 'Nataline Stanex');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (340, 'Ornamental Railings', '2024/03/13', 'Kenyon Prangley');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (341, 'Exterior Signage', '2023/11/08', 'Winnie Winstanley');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (342, 'Plumbing & Medical Gas', '2023/05/28', 'Hugh Kleewein');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (343, 'Casework', '2023/05/17', 'Euphemia Hafford');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (344, 'Framing (Wood)', '2024/03/14', 'Cathrine Clarke');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (345, 'Retaining Wall and Brick Pavers', '2023/06/08', 'Celia Lodin');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (346, 'Termite Control', '2023/06/10', 'Odie Suddell');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (347, 'Landscaping & Irrigation', '2023/07/25', 'Brade Dauby');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (348, 'Prefabricated Aluminum Metal Canopies', '2023/11/20', 'Fredric Tancock');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (349, 'Structural & Misc Steel Erection', '2023/05/25', 'Findley Lapree');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (350, 'Wall Protection', '2023/09/28', 'Reta Brunotti');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (351, 'Doors, Frames & Hardware', '2023/06/24', 'Hamilton Hugin');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (352, 'Exterior Signage', '2023/11/21', 'Ardisj Sachno');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (353, 'Rebar & Wire Mesh Install', '2023/11/25', 'Charlene Aggus');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (354, 'Electrical', '2023/11/28', 'Morena Dimblebee');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (355, 'Drilled Shafts', '2023/05/25', 'Edeline Duchesne');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (356, 'Casework', '2023/06/18', 'Jim Grelak');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (357, 'Hard Tile & Stone', '2023/07/13', 'Pavlov Hitter');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (358, 'HVAC', '2023/12/01', 'Stuart Storms');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (359, 'Structural & Misc Steel Erection', '2023/05/09', 'Ferdinand Prantoni');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (360, 'Framing (Steel)', '2023/06/11', 'Ingrim Jakubowski');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (361, 'Electrical', '2023/10/11', 'Padraig Deaves');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (362, 'Masonry & Precast', '2023/07/04', 'Annabell Coe');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (363, 'Drywall & Acoustical (MOB)', '2023/09/29', 'Barn Moffett');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (364, 'Granite Surfaces', '2024/02/28', 'Franciska Marin');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (365, 'Roofing (Asphalt)', '2023/04/28', 'Norma Danser');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (366, 'Waterproofing & Caulking', '2023/12/05', 'Gina Shackel');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (367, 'Site Furnishings', '2023/05/23', 'Tailor Dooley');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (368, 'Electrical and Fire Alarm', '2024/01/14', 'Orelia Bartels');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (369, 'Glass & Glazing', '2023/09/01', 'Karlotte Chace');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (370, 'Electrical and Fire Alarm', '2023/11/15', 'Jaimie Burkert');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (371, 'Marlite Panels (FED)', '2024/01/27', 'Woodie Paddington');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (372, 'Hard Tile & Stone', '2024/03/20', 'Corrina Gudgen');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (373, 'Glass & Glazing', '2023/06/22', 'Saundra Placide');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (374, 'Structural and Misc Steel (Fabrication)', '2023/07/21', 'Laural Deboick');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (375, 'Doors, Frames & Hardware', '2023/04/15', 'Auria Howatt');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (376, 'Painting & Vinyl Wall Covering', '2023/07/29', 'Dietrich Jirousek');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (377, 'Exterior Signage', '2023/09/30', 'Crysta Whatsize');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (378, 'Temp Fencing, Decorative Fencing and Gates', '2024/01/09', 'Renell Schellig');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (379, 'Curb & Gutter', '2024/01/15', 'Patin Wanstall');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (380, 'Temp Fencing, Decorative Fencing and Gates', '2023/11/15', 'Sterling Larcher');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (381, 'Ornamental Railings', '2024/03/20', 'Huntley Cuthbert');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (382, 'Site Furnishings', '2023/09/10', 'Donnamarie Haddock');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (383, 'Site Furnishings', '2024/03/01', 'Zelma Keam');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (384, 'Framing (Steel)', '2024/04/09', 'Forest Ferries');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (385, 'Termite Control', '2023/11/20', 'Bianka Leaman');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (386, 'Epoxy Flooring', '2024/02/10', 'Jeff Oglevie');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (387, 'Roofing (Metal)', '2024/02/22', 'Editha Gonnard');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (388, 'Epoxy Flooring', '2024/01/01', 'Corny Messitt');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (389, 'HVAC', '2023/08/06', 'Werner Greir');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (390, 'Granite Surfaces', '2024/01/22', 'Chaim Monard');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (391, 'Glass & Glazing', '2023/11/02', 'Clarabelle Maryon');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (392, 'Roofing (Asphalt)', '2023/10/20', 'Thedric McCrostie');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (393, 'Painting & Vinyl Wall Covering', '2023/04/24', 'Pandora Rodliff');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (394, 'Sitework & Site Utilities', '2023/12/04', 'Karyn Parham');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (395, 'Structural & Misc Steel Erection', '2024/02/14', 'Adrien Sephton');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (396, 'Roofing (Metal)', '2024/03/05', 'Bren Meaton');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (397, 'Exterior Signage', '2024/04/12', 'Mead Whittek');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (398, 'Rebar & Wire Mesh Install', '2024/02/17', 'Sergeant Guslon');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (399, 'Hard Tile & Stone', '2023/07/12', 'Theresina Bolf');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (400, 'EIFS', '2024/01/21', 'Bucky Breckon');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (401, 'Site Furnishings', '2024/01/24', 'Bartolomeo Pashby');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (402, 'Prefabricated Aluminum Metal Canopies', '2023/12/04', 'Opal Ruggs');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (403, 'Doors, Frames & Hardware', '2023/12/14', 'Betta Kingsworth');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (404, 'Rebar & Wire Mesh Install', '2023/09/11', 'Sallyanne Blenkhorn');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (405, 'Painting & Vinyl Wall Covering', '2023/06/08', 'Vonny Gheorghe');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (406, 'Landscaping & Irrigation', '2023/11/26', 'Ogdon Franchioni');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (407, 'HVAC', '2023/09/15', 'Sukey Roggero');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (408, 'Drywall & Acoustical (MOB)', '2024/01/15', 'Harmonia Wiggington');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (409, 'Fire Protection', '2023/11/03', 'Eugenius Thibodeaux');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (410, 'Structural and Misc Steel (Fabrication)', '2024/01/06', 'Ariana Lilywhite');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (411, 'Waterproofing & Caulking', '2023/10/29', 'Hester Deaves');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (412, 'Roofing (Metal)', '2023/09/16', 'Ronald Turrell');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (413, 'Exterior Signage', '2023/05/21', 'Keene Johnston');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (414, 'Framing (Steel)', '2023/06/28', 'Llywellyn Prynne');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (415, 'Construction Clean and Final Clean', '2023/10/30', 'Renato Dolling');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (416, 'Ornamental Railings', '2023/10/03', 'Zachariah Hirthe');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (417, 'Wall Protection', '2023/11/28', 'Wylie Jachimak');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (418, 'Marlite Panels (FED)', '2024/03/05', 'Grannie Croix');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (419, 'Epoxy Flooring', '2023/06/16', 'Heidie Stroton');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (420, 'Curb & Gutter', '2023/09/12', 'Urbanus Fergie');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (421, 'Drywall & Acoustical (MOB)', '2024/03/05', 'Noble Josiah');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (422, 'Waterproofing & Caulking', '2023/05/04', 'Shelby Giraux');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (423, 'Construction Clean and Final Clean', '2023/12/25', 'Jordanna Knowlden');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (424, 'Termite Control', '2023/10/26', 'Becky Skaife d''Ingerthorpe');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (425, 'Site Furnishings', '2024/03/09', 'Gabrila Linden');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (426, 'Roofing (Metal)', '2024/03/17', 'Ingemar Braybrookes');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (427, 'Soft Flooring and Base', '2024/02/02', 'Morlee Allcroft');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (428, 'Waterproofing & Caulking', '2023/08/25', 'Payton Willes');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (429, 'Electrical and Fire Alarm', '2023/09/01', 'Charmain Cheek');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (430, 'Painting & Vinyl Wall Covering', '2023/07/19', 'Wendi Lillee');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (431, 'Electrical', '2023/08/02', 'Drucill Ledwich');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (432, 'Wall Protection', '2023/08/08', 'Nikolai Jablonski');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (433, 'Fire Sprinkler System', '2023/08/08', 'Diann Bagniuk');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (434, 'Roofing (Metal)', '2023/08/30', 'Philip Kinane');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (435, 'Drywall & Acoustical (FED)', '2023/06/29', 'Kiri Gebbe');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (436, 'Fire Protection', '2023/06/10', 'Ingunna Gilfether');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (437, 'Soft Flooring and Base', '2023/07/17', 'Andrey Osgorby');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (438, 'Drilled Shafts', '2024/03/16', 'Consuelo Hanmer');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (439, 'Fire Sprinkler System', '2024/01/30', 'Afton Mulcahy');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (440, 'Plumbing & Medical Gas', '2023/08/14', 'Tiebold McCloy');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (441, 'Plumbing & Medical Gas', '2024/03/09', 'Jocelin Maidlow');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (442, 'Termite Control', '2023/05/22', 'Devondra Piggens');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (443, 'Fire Sprinkler System', '2024/03/29', 'Waite Pennetti');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (444, 'Masonry', '2024/02/01', 'Ketti Campa');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (445, 'Masonry & Precast', '2023/07/19', 'Ellynn Shilito');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (446, 'Wall Protection', '2024/01/27', 'Eal Fewell');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (447, 'Soft Flooring and Base', '2023/09/18', 'Nonnah Pehrsson');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (448, 'Masonry & Precast', '2023/04/16', 'Camey Oxlee');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (449, 'Drywall & Acoustical (MOB)', '2023/09/26', 'Raimondo Marousek');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (450, 'Drywall & Acoustical (FED)', '2024/03/29', 'Janelle MacKnight');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (451, 'Framing (Wood)', '2023/04/16', 'Chad Podbury');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (452, 'Painting & Vinyl Wall Covering', '2023/08/31', 'Felicity Bleue');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (453, 'Structural and Misc Steel (Fabrication)', '2024/03/25', 'Nissy Esch');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (454, 'Drywall & Acoustical (FED)', '2024/02/01', 'Anthia Kneebone');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (455, 'Soft Flooring and Base', '2023/09/17', 'Maurene Rabbitts');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (456, 'EIFS', '2023/12/19', 'Daphene Bellward');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (457, 'Rebar & Wire Mesh Install', '2024/01/05', 'Aaren Surgeon');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (458, 'Asphalt Paving', '2024/02/19', 'Trueman Dunnet');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (459, 'Wall Protection', '2024/01/05', 'Sander Jordanson');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (460, 'Masonry & Precast', '2023/04/25', 'Florance Pashen');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (461, 'Prefabricated Aluminum Metal Canopies', '2023/09/02', 'Brendin Dumphries');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (462, 'EIFS', '2023/07/12', 'Tara Huett');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (463, 'Wall Protection', '2023/06/22', 'Morgan Le Frank');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (464, 'Electrical', '2023/06/18', 'Ware Cornell');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (465, 'Masonry & Precast', '2024/01/30', 'Arleyne Garner');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (466, 'EIFS', '2023/10/23', 'Elaina Foulgham');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (467, 'Glass & Glazing', '2023/05/02', 'Phylys Geggus');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (468, 'EIFS', '2023/09/26', 'Danita McIlvoray');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (469, 'Ornamental Railings', '2024/02/17', 'Konstance Torbard');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (470, 'Doors, Frames & Hardware', '2023/08/14', 'Tomi McCathie');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (471, 'Temp Fencing, Decorative Fencing and Gates', '2024/04/13', 'Carr Godfray');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (472, 'Electrical and Fire Alarm', '2023/06/01', 'Raeann Simacek');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (473, 'Retaining Wall and Brick Pavers', '2023/06/16', 'Melody Eassom');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (474, 'Exterior Signage', '2023/06/17', 'Bendix Farman');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (475, 'Fire Protection', '2023/05/26', 'Melodie Kubicek');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (476, 'Structural & Misc Steel Erection', '2023/07/24', 'Sebastien Melchior');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (477, 'Retaining Wall and Brick Pavers', '2023/11/03', 'Bryna Guinness');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (478, 'Hard Tile & Stone', '2023/06/21', 'Clemmie Leyman');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (479, 'Soft Flooring and Base', '2023/10/04', 'Horace Kendal');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (480, 'Doors, Frames & Hardware', '2023/06/21', 'Rriocard Reah');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (481, 'Roofing (Metal)', '2023/12/12', 'Berty Hames');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (482, 'Landscaping & Irrigation', '2024/02/19', 'Aurlie Cremins');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (483, 'Hard Tile & Stone', '2023/04/25', 'Vivyanne Veneur');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (484, 'Drywall & Acoustical (MOB)', '2023/04/16', 'Brodie Filgate');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (485, 'Masonry & Precast', '2024/02/14', 'Eddie Spare');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (486, 'EIFS', '2023/11/23', 'Courtnay Rothman');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (487, 'Glass & Glazing', '2023/07/25', 'Harmonie Crabbe');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (488, 'Construction Clean and Final Clean', '2023/12/02', 'Cullie Milton');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (489, 'Masonry & Precast', '2023/08/21', 'Ronnie Hulme');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (490, 'Overhead Doors', '2024/01/30', 'Verina Urry');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (491, 'Curb & Gutter', '2023/12/20', 'Thorndike Zapatero');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (492, 'Temp Fencing, Decorative Fencing and Gates', '2023/10/03', 'Melissa Benian');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (493, 'RF Shielding', '2023/06/12', 'Loni Clifft');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (494, 'Plumbing & Medical Gas', '2023/09/02', 'Marcie Este');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (495, 'Elevator', '2023/05/03', 'Lewiss Nisbet');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (496, 'Site Furnishings', '2024/03/08', 'Jimmy Begbie');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (497, 'Wall Protection', '2023/10/22', 'Daryle Riccetti');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (498, 'Hard Tile & Stone', '2023/07/20', 'Aubine Flintoft');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (499, 'Wall Protection', '2023/05/01', 'Davita Rhelton');
insert into categoria (CATEGORIA_ID, NOME, DTAINCLUSAO, USUINCLUSAO) values (500, 'Epoxy Flooring', '2024/03/29', 'Wit Dunkinson');
