CREATE DATABASE ERP_DB;

USE ERP_DB;

-- Tabela Categoria
CREATE TABLE CATEGORIA (
    CATEGORIA_ID INT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DTAINCLUSAO DATETIME NOT NULL,
    USUINCLUSAO VARCHAR(100) NOT NULL
);

-- Tabela Produto
CREATE TABLE PRODUTO (
    PRODUTO_ID INT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    PRECO DECIMAL(10, 2) NOT NULL,
    CATEGORIA_ID INT,
    FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA(CATEGORIA_ID)
);

-- Tabela Cliente
CREATE TABLE CLIENTE (
    CLIENTE_ID INT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    ENDERECO VARCHAR(255) NOT NULL,
    CIDADE VARCHAR(50) NOT NULL,
    ESTADO VARCHAR(50) NOT NULL,
    TELEFONE VARCHAR(20),
    DTAINCLUSA DATETIME NOT NULL
);

-- Tabela Pedido
CREATE TABLE PEDIDO (
    PEDIDO_ID INT PRIMARY KEY AUTO_INCREMENT,
    CLIENTE_ID INT NOT NULL,
    DTAPEDIDO DATE NOT NULL,
    DTAENTREGA DATE,
    TOTAL DECIMAL(10,2) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    FORMA_PAGAMENTO VARCHAR(50) NOT NULL,
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(CLIENTE_ID)
);

-- Tabela de associação entre Produto e Pedido
CREATE TABLE PEDIDO_PRODUTO (
    PEDIDO_ID INT,
    PRODUTO_ID INT,
    QUANTIDADE INT NOT NULL,
    PRECO_UNITARIO DECIMAL(10, 2) NOT NULL,
    PRIMARY KEY (PEDIDO_ID, PRODUTO_ID),
    FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDO(PEDIDO_ID),
    FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO(PRODUTO_ID)
);

-- Tabela de associação entre Categoria e Produto
CREATE TABLE CATEGORIA_PRODUTO (
    CATEGORIA_ID INT,
    PRODUTO_ID INT,
    PRIMARY KEY (CATEGORIA_ID, PRODUTO_ID),
    FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA(CATEGORIA_ID),
    FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO(PRODUTO_ID)
);

-- Tabela de associação entre Pedido e Cliente
CREATE TABLE PEDIDO_CLIENTE (
    PEDIDO_ID INT,
    CLIENTE_ID INT,
    PRIMARY KEY (PEDIDO_ID, CLIENTE_ID),
    FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDO(PEDIDO_ID),
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(CLIENTE_ID)
);
